Overall_caseload_and_referrals = {'sheet_name': 'Case Status Split', 'table_name': 'Overall caseload and referrals', 'row_names': ['Number referrals', 'Number unique referrals', 'Referrals accepted', 'Referrals refused', 'Number open cases', 'Number closed cases'], 'placeholder_text': {'Number referrals': 'todo', 'Number unique referrals': 'todo', 'Referrals accepted': 'todo', 'Referrals refused': 'todo', 'Number open cases': 'todo', 'Number closed cases': 'todo'}}

CIC_CLA_caseload_and_referrals = {'sheet_name': 'Case Status Split', 'table_name': 'CIC/CLA caseload and referrals', 'row_names': ['Number referrals', 'Number unique referrals', 'Referrals accepted', 'Referrals refused', 'Number open cases', 'Number closed cases'], 'placeholder_text': {'Number referrals': 'todo', 'Number unique referrals': 'todo', 'Referrals accepted': 'todo', 'Referrals refused': 'todo', 'Number open cases': 'todo', 'Number closed cases': 'todo'}}

SEN_caseload_and_referrals = {'sheet_name': 'Case Status Split', 'table_name': 'SEN caseload and referrals', 'row_names': ['Number referrals', 'Number unique referrals', 'Referrals accepted', 'Referrals refused', 'Number open cases', 'Number closed cases'], 'placeholder_text': {'Number referrals': 'todo', 'Number unique referrals': 'todo', 'Referrals accepted': 'todo', 'Referrals refused': 'todo', 'Number open cases': 'todo', 'Number closed cases': 'todo'}}

EHCP_caseload_and_referrals = {'sheet_name': 'Case Status Split', 'table_name': 'EHCP caseload and referrals', 'row_names': ['Number referrals', 'Number unique referrals', 'Referrals accepted', 'Referrals refused', 'Number open cases', 'Number closed cases'], 'placeholder_text': {'Number referrals': 'todo', 'Number unique referrals': 'todo', 'Referrals accepted': 'todo', 'Referrals refused': 'todo', 'Number open cases': 'todo', 'Number closed cases': 'todo'}}

CRAVEN_caseload_and_referrals = {'sheet_name': 'Case Status Split', 'table_name': 'CRAVEN caseload and referrals', 'row_names': ['Number referrals', 'Number unique referrals', 'Referrals accepted', 'Referrals refused', 'Number open cases', 'Number closed cases'], 'placeholder_text': {'Number referrals': 'todo', 'Number unique referrals': 'todo', 'Referrals accepted': 'todo', 'Referrals refused': 'todo', 'Number open cases': 'todo', 'Number closed cases': 'todo'}}

BRADFORD_DISTRICT_caseload_and_referrals = {'sheet_name': 'Case Status Split', 'table_name': 'BRADFORD DISTRICT caseload and referrals', 'row_names': ['Number referrals', 'Number unique referrals', 'Referrals accepted', 'Referrals refused', 'Number open cases', 'Number closed cases'], 'placeholder_text': {'Number referrals': 'todo', 'Number unique referrals': 'todo', 'Referrals accepted': 'todo', 'Referrals refused': 'todo', 'Number open cases': 'todo', 'Number closed cases': 'todo'}}

All_Referrals_by_demographics = {'sheet_name': 'Demographic split ', 'table_name': 'All Referrals by demographics', 'row_names': ['Age 4', 'Age 5', 'Age 6', 'Age 7', 'Age 8', 'Age 9', 'Age 10', 'Age 11', 'Age 12', 'Age 13', 'Age 14', 'Age 15', 'Age 16', 'Age 17', 'Age 18', 'Age 19', 'Age 20', 'Age 21', 'Age 22', 'Age 23', 'Age 24', 'Age 25', 'Out of age range (data input error)', 'Female', 'Male', 'Non-Binary', 'Transgender', 'Unknown', 'African', 'Arab', 'Bangladeshi', 'Caribbean', 'Central and Eastern European', 'Chinese', 'Gypsy/Roma/Traveller', 'Indian', 'Irish', 'Latin America', 'Pakistani', 'White and Asian', 'White and Black African', 'White and Black Carribean', 'White British', 'Any other Asian background', 'Any other Black background', 'Any other Ethnic group', 'Any other Mixed background', 'Any other White background', 'Unknown'], 'placeholder_text': {'Age 4': 'todo', 'Age 5': 'todo', 'Age 6': 'todo', 'Age 7': 'todo', 'Age 8': 'todo', 'Age 9': 'todo', 'Age 10': 'todo', 'Age 11': 'todo', 'Age 12': 'todo', 'Age 13': 'todo', 'Age 14': 'todo', 'Age 15': 'todo', 'Age 16': 'todo', 'Age 17': 'todo', 'Age 18': 'todo', 'Age 19': 'todo', 'Age 20': 'todo', 'Age 21': 'todo', 'Age 22': 'todo', 'Age 23': 'todo', 'Age 24': 'todo', 'Age 25': 'todo', 'Out of age range (data input error)': 'todo', 'Female': 'todo', 'Male': 'todo', 'Non-Binary': 'todo', 'Transgender': 'todo', 'Unknown': 'todo', 'African': 'todo', 'Arab': 'todo', 'Bangladeshi': 'todo', 'Caribbean': 'todo', 'Central and Eastern European': 'todo', 'Chinese': 'todo', 'Gypsy/Roma/Traveller': 'todo', 'Indian': 'todo', 'Irish': 'todo', 'Latin America': 'todo', 'Pakistani': 'todo', 'White and Asian': 'todo', 'White and Black African': 'todo', 'White and Black Carribean': 'todo', 'White British': 'todo', 'Any other Asian background': 'todo', 'Any other Black background': 'todo', 'Any other Ethnic group': 'todo', 'Any other Mixed background': 'todo', 'Any other White background': 'todo'}}

All_CIC_CLA_Referrals_by_demographics = {'sheet_name': 'Demographic split ', 'table_name': 'All CIC/CLA Referrals by demographics', 'row_names': ['Age 4', 'Age 5', 'Age 6', 'Age 7', 'Age 8', 'Age 9', 'Age 10', 'Age 11', 'Age 12', 'Age 13', 'Age 14', 'Age 15', 'Age 16', 'Age 17', 'Age 18', 'Age 19', 'Age 20', 'Age 21', 'Age 22', 'Age 23', 'Age 24', 'Age 25', 'Out of Age', 'Female', 'Male', 'Non-Binary', 'Transgender', 'Unknown', 'African', 'Arab', 'Bangladeshi', 'Caribbean', 'Central and Eastern European', 'Chinese', 'Gypsy/Roma/Traveller', 'Indian', 'Irish', 'Latin America', 'Pakistani', 'White and Asian', 'White and Black African', 'White and Black Carribean', 'White British', 'Any other Asian background', 'Any other Black background', 'Any other Ethnic group', 'Any other Mixed background', 'Any other White background', 'Unknown'], 'placeholder_text': {'Age 4': 'todo', 'Age 5': 'todo', 'Age 6': 'todo', 'Age 7': 'todo', 'Age 8': 'todo', 'Age 9': 'todo', 'Age 10': 'todo', 'Age 11': 'todo', 'Age 12': 'todo', 'Age 13': 'todo', 'Age 14': 'todo', 'Age 15': 'todo', 'Age 16': 'todo', 'Age 17': 'todo', 'Age 18': 'todo', 'Age 19': 'todo', 'Age 20': 'todo', 'Age 21': 'todo', 'Age 22': 'todo', 'Age 23': 'todo', 'Age 24': 'todo', 'Age 25': 'todo', 'Out of Age': 'todo', 'Female': 'todo', 'Male': 'todo', 'Non-Binary': 'todo', 'Transgender': 'todo', 'Unknown': 'todo', 'African': 'todo', 'Arab': 'todo', 'Bangladeshi': 'todo', 'Caribbean': 'todo', 'Central and Eastern European': 'todo', 'Chinese': 'todo', 'Gypsy/Roma/Traveller': 'todo', 'Indian': 'todo', 'Irish': 'todo', 'Latin America': 'todo', 'Pakistani': 'todo', 'White and Asian': 'todo', 'White and Black African': 'todo', 'White and Black Carribean': 'todo', 'White British': 'todo', 'Any other Asian background': 'todo', 'Any other Black background': 'todo', 'Any other Ethnic group': 'todo', 'Any other Mixed background': 'todo', 'Any other White background': 'todo'}}

All_SEN_Referrals_by_demographics = {'sheet_name': 'Demographic split ', 'table_name': 'All SEN Referrals by demographics', 'row_names': ['Age 4', 'Age 5', 'Age 6', 'Age 7', 'Age 8', 'Age 9', 'Age 10', 'Age 11', 'Age 12', 'Age 13', 'Age 14', 'Age 15', 'Age 16', 'Age 17', 'Age 18', 'Age 19', 'Age 20', 'Age 21', 'Age 22', 'Age 23', 'Age 24', 'Age 25', 'Female', 'Male', 'Non-Binary', 'Transgender', 'Unknown', 'African', 'Arab', 'Bangladeshi', 'Caribbean', 'Central and Eastern European', 'Chinese', 'Gypsy/Roma/Traveller', 'Indian', 'Irish', 'Latin America', 'Pakistani', 'White and Asian', 'White and Black African', 'White and Black Carribean', 'White British', 'Any other Asian background', 'Any other Black background', 'Any other Ethnic group', 'Any other Mixed background', 'Any other White background', 'Unknown'], 'placeholder_text': {'Age 4': 'todo', 'Age 5': 'todo', 'Age 6': 'todo', 'Age 7': 'todo', 'Age 8': 'todo', 'Age 9': 'todo', 'Age 10': 'todo', 'Age 11': 'todo', 'Age 12': 'todo', 'Age 13': 'todo', 'Age 14': 'todo', 'Age 15': 'todo', 'Age 16': 'todo', 'Age 17': 'todo', 'Age 18': 'todo', 'Age 19': 'todo', 'Age 20': 'todo', 'Age 21': 'todo', 'Age 22': 'todo', 'Age 23': 'todo', 'Age 24': 'todo', 'Age 25': 'todo', 'Female': 'todo', 'Male': 'todo', 'Non-Binary': 'todo', 'Transgender': 'todo', 'Unknown': 'todo', 'African': 'todo', 'Arab': 'todo', 'Bangladeshi': 'todo', 'Caribbean': 'todo', 'Central and Eastern European': 'todo', 'Chinese': 'todo', 'Gypsy/Roma/Traveller': 'todo', 'Indian': 'todo', 'Irish': 'todo', 'Latin America': 'todo', 'Pakistani': 'todo', 'White and Asian': 'todo', 'White and Black African': 'todo', 'White and Black Carribean': 'todo', 'White British': 'todo', 'Any other Asian background': 'todo', 'Any other Black background': 'todo', 'Any other Ethnic group': 'todo', 'Any other Mixed background': 'todo', 'Any other White background': 'todo'}}

All_EHCP_Referrals_by_demographics = {'sheet_name': 'Demographic split ', 'table_name': 'All EHCP Referrals by demographics', 'row_names': ['Age 4', 'Age 5', 'Age 6', 'Age 7', 'Age 8', 'Age 9', 'Age 10', 'Age 11', 'Age 12', 'Age 13', 'Age 14', 'Age 15', 'Age 16', 'Age 17', 'Age 18', 'Age 19', 'Age 20', 'Age 21', 'Age 22', 'Age 23', 'Age 24', 'Age 25', 'Female', 'Male', 'Non-Binary', 'Transgender', 'Unknown', 'African', 'Arab', 'Bangladeshi', 'Caribbean', 'Central and Eastern European', 'Chinese', 'Gypsy/Roma/Traveller', 'Indian', 'Irish', 'Latin America', 'Pakistani', 'White and Asian', 'White and Black African', 'White and Black Carribean', 'White British', 'Any other Asian background', 'Any other Black background', 'Any other Ethnic group', 'Any other Mixed background', 'Any other White background', 'Unknown'], 'placeholder_text': {'Age 4': 'todo', 'Age 5': 'todo', 'Age 6': 'todo', 'Age 7': 'todo', 'Age 8': 'todo', 'Age 9': 'todo', 'Age 10': 'todo', 'Age 11': 'todo', 'Age 12': 'todo', 'Age 13': 'todo', 'Age 14': 'todo', 'Age 15': 'todo', 'Age 16': 'todo', 'Age 17': 'todo', 'Age 18': 'todo', 'Age 19': 'todo', 'Age 20': 'todo', 'Age 21': 'todo', 'Age 22': 'todo', 'Age 23': 'todo', 'Age 24': 'todo', 'Age 25': 'todo', 'Female': 'todo', 'Male': 'todo', 'Non-Binary': 'todo', 'Transgender': 'todo', 'Unknown': 'todo', 'African': 'todo', 'Arab': 'todo', 'Bangladeshi': 'todo', 'Caribbean': 'todo', 'Central and Eastern European': 'todo', 'Chinese': 'todo', 'Gypsy/Roma/Traveller': 'todo', 'Indian': 'todo', 'Irish': 'todo', 'Latin America': 'todo', 'Pakistani': 'todo', 'White and Asian': 'todo', 'White and Black African': 'todo', 'White and Black Carribean': 'todo', 'White British': 'todo', 'Any other Asian background': 'todo', 'Any other Black background': 'todo', 'Any other Ethnic group': 'todo', 'Any other Mixed background': 'todo', 'Any other White background': 'todo'}}

All_CRAVEN_Referrals_by_demographics = {'sheet_name': 'Demographic split ', 'table_name': 'All CRAVEN Referrals by demographics', 'row_names': ['Age 4', 'Age 5', 'Age 6', 'Age 7', 'Age 8', 'Age 9', 'Age 10', 'Age 11', 'Age 12', 'Age 13', 'Age 14', 'Age 15', 'Age 16', 'Age 17', 'Age 18', 'Age 19', 'Age 20', 'Age 21', 'Age 22', 'Age 23', 'Age 24', 'Age 25', 'Female', 'Male', 'Non-Binary', 'Transgender', 'African', 'Arab', 'Bangladeshi', 'Caribbean', 'Central and Eastern European', 'Chinese', 'Gypsy/Roma/Traveller', 'Indian', 'Irish', 'Latin America', 'Pakistani', 'White and Asian', 'White and Black African', 'White and Black Carribean', 'White British', 'Any other Asian background', 'Any other Black background', 'Any other Ethnic group', 'Any other Mixed background', 'Any other White background', 'Unknown'], 'placeholder_text': {'Age 4': 'todo', 'Age 5': 'todo', 'Age 6': 'todo', 'Age 7': 'todo', 'Age 8': 'todo', 'Age 9': 'todo', 'Age 10': 'todo', 'Age 11': 'todo', 'Age 12': 'todo', 'Age 13': 'todo', 'Age 14': 'todo', 'Age 15': 'todo', 'Age 16': 'todo', 'Age 17': 'todo', 'Age 18': 'todo', 'Age 19': 'todo', 'Age 20': 'todo', 'Age 21': 'todo', 'Age 22': 'todo', 'Age 23': 'todo', 'Age 24': 'todo', 'Age 25': 'todo', 'Female': 'todo', 'Male': 'todo', 'Non-Binary': 'todo', 'Transgender': 'todo', 'African': 'todo', 'Arab': 'todo', 'Bangladeshi': 'todo', 'Caribbean': 'todo', 'Central and Eastern European': 'todo', 'Chinese': 'todo', 'Gypsy/Roma/Traveller': 'todo', 'Indian': 'todo', 'Irish': 'todo', 'Latin America': 'todo', 'Pakistani': 'todo', 'White and Asian': 'todo', 'White and Black African': 'todo', 'White and Black Carribean': 'todo', 'White British': 'todo', 'Any other Asian background': 'todo', 'Any other Black background': 'todo', 'Any other Ethnic group': 'todo', 'Any other Mixed background': 'todo', 'Any other White background': 'todo', 'Unknown': 'todo'}}

BRADFORD_DISTRICT_Referrals_by_demographics = {'sheet_name': 'Demographic split ', 'table_name': 'BRADFORD DISTRICT Referrals by demographics', 'row_names': ['Age 4', 'Age 5', 'Age 6', 'Age 7', 'Age 8', 'Age 9', 'Age 10', 'Age 11', 'Age 12', 'Age 13', 'Age 14', 'Age 15', 'Age 16', 'Age 17', 'Age 18', 'Age 19', 'Age 20', 'Age 21', 'Age 22', 'Age 23', 'Age 24', 'Age 25', 'Out of age range (data input error)', 'Female', 'Male', 'Non-Binary', 'Transgender', 'Unknown', 'African', 'Arab', 'Bangladeshi', 'Caribbean', 'Central and Eastern European', 'Chinese', 'Gypsy/Roma/Traveller', 'Indian', 'Irish', 'Latin America', 'Pakistani', 'White and Asian', 'White and Black African', 'White and Black Carribean', 'White British', 'Any other Asian background', 'Any other Black background', 'Any other Ethnic group', 'Any other Mixed background', 'Any other White background', 'Unknown'], 'placeholder_text': {'Age 4': 'todo', 'Age 5': 'todo', 'Age 6': 'todo', 'Age 7': 'todo', 'Age 8': 'todo', 'Age 9': 'todo', 'Age 10': 'todo', 'Age 11': 'todo', 'Age 12': 'todo', 'Age 13': 'todo', 'Age 14': 'todo', 'Age 15': 'todo', 'Age 16': 'todo', 'Age 17': 'todo', 'Age 18': 'todo', 'Age 19': 'todo', 'Age 20': 'todo', 'Age 21': 'todo', 'Age 22': 'todo', 'Age 23': 'todo', 'Age 24': 'todo', 'Age 25': 'todo', 'Out of age range (data input error)': 'todo', 'Female': 'todo', 'Male': 'todo', 'Non-Binary': 'todo', 'Transgender': 'todo', 'Unknown': 'todo', 'African': 'todo', 'Arab': 'todo', 'Bangladeshi': 'todo', 'Caribbean': 'todo', 'Central and Eastern European': 'todo', 'Chinese': 'todo', 'Gypsy/Roma/Traveller': 'todo', 'Indian': 'todo', 'Irish': 'todo', 'Latin America': 'todo', 'Pakistani': 'todo', 'White and Asian': 'todo', 'White and Black African': 'todo', 'White and Black Carribean': 'todo', 'White British': 'todo', 'Any other Asian background': 'todo', 'Any other Black background': 'todo', 'Any other Ethnic group': 'todo', 'Any other Mixed background': 'todo', 'Any other White background': 'todo'}}

Source_of_All_Referrals = {'sheet_name': 'Referral Source', 'table_name': 'Source of All Referrals', 'row_names': ['GP services', 'Other Primary Health Care', 'Self', 'Carer', 'Social Services', 'Education Service', 'Housing Service', 'Police', 'Youth Offending Service', 'School Nurse', 'Hospital-based Paediatrics', 'Community-based Paediatrics', 'Voluntary Sector', 'Accident And Emergency Department', 'Other secondary care specialty', 'Out of Area Agency', 'Drug Action Team / Drug Misuse Agency', 'Other service or agency', 'Single Point of Access Service', 'Internal Referral', 'CAMHS Core/Step down', 'CAMHS Waiting List', 'CAMHS Crisis', 'Transfer by graduation from Child Adolescent Mental Health Services to Adult', 'VCS', 'Unknown'], 'placeholder_text': {'GP services': 'todo', 'Other Primary Health Care': 'todo', 'Self': 'todo', 'Carer': 'todo', 'Social Services': 'todo', 'Education Service': 'todo', 'Housing Service': 'todo', 'Police': 'todo', 'Youth Offending Service': 'todo', 'School Nurse': 'todo', 'Hospital-based Paediatrics': 'todo', 'Community-based Paediatrics': 'todo', 'Voluntary Sector': 'todo', 'Accident And Emergency Department': 'todo', 'Other secondary care specialty': 'todo', 'Out of Area Agency': 'todo', 'Drug Action Team / Drug Misuse Agency': 'todo', 'Other service or agency': 'todo', 'Single Point of Access Service': 'todo', 'Internal Referral': 'todo', 'CAMHS Core/Step down': 'todo', 'CAMHS Waiting List': 'todo', 'CAMHS Crisis': 'todo', 'Transfer by graduation from Child Adolescent Mental Health Services to Adult': 'todo', 'VCS': 'todo', 'Unknown': 'todo'}}

Source_of_Referrals___CIC_CLA = {'sheet_name': 'Referral Source', 'table_name': 'Source of Referrals - CIC/CLA', 'row_names': ['GP services', 'Other Primary Health Care', 'Self', 'Carer', 'Social Services', 'Education Service', 'Housing Service', 'Police', 'School Nurse', 'Hospital-based Paediatrics', 'Community-based Paediatrics', 'Voluntary Sector', 'Accident And Emergency Department', 'Other secondary care specialty', 'Out of Area Agency', 'Drug Action Team / Drug Misuse Agency', 'Other service or agency', 'Single Point of Access Service', 'Internal Referral', 'CAMHS Core/Step down', 'CAMHS Waiting List', 'CAMHS Crisis', 'VCS', 'Permanent transfer from another Mental Health NHS Trust', 'Unknown'], 'placeholder_text': {'GP services': 'todo', 'Other Primary Health Care': 'todo', 'Self': 'todo', 'Carer': 'todo', 'Social Services': 'todo', 'Education Service': 'todo', 'Housing Service': 'todo', 'Police': 'todo', 'School Nurse': 'todo', 'Hospital-based Paediatrics': 'todo', 'Community-based Paediatrics': 'todo', 'Voluntary Sector': 'todo', 'Accident And Emergency Department': 'todo', 'Other secondary care specialty': 'todo', 'Out of Area Agency': 'todo', 'Drug Action Team / Drug Misuse Agency': 'todo', 'Other service or agency': 'todo', 'Single Point of Access Service': 'todo', 'Internal Referral': 'todo', 'CAMHS Core/Step down': 'todo', 'CAMHS Waiting List': 'todo', 'CAMHS Crisis': 'todo', 'VCS': 'todo', 'Permanent transfer from another Mental Health NHS Trust': 'todo', 'Unknown': 'todo'}}

Source_of_Referrals___SEN = {'sheet_name': 'Referral Source', 'table_name': 'Source of Referrals - SEN', 'row_names': ['GP services', 'Other Primary Health Care', 'Self', 'Carer', 'Social Services', 'Education Service', 'Housing Service', 'Police', 'School Nurse', 'Hospital-based Paediatrics', 'Community-based Paediatrics', 'Voluntary Sector', 'Accident And Emergency Department', 'Other secondary care specialty', 'Out of Area Agency', 'Drug Action Team / Drug Misuse Agency', 'Other service or agency', 'Single Point of Access Service', 'Internal Referral', 'CAMHS Core/Step down', 'CAMHS Waiting List', 'CAMHS Crisis', 'VCS', 'Permanent transfer from another Mental Health NHS Trust', 'Unknown'], 'placeholder_text': {'GP services': 'todo', 'Other Primary Health Care': 'todo', 'Self': 'todo', 'Carer': 'todo', 'Social Services': 'todo', 'Education Service': 'todo', 'Housing Service': 'todo', 'Police': 'todo', 'School Nurse': 'todo', 'Hospital-based Paediatrics': 'todo', 'Community-based Paediatrics': 'todo', 'Voluntary Sector': 'todo', 'Accident And Emergency Department': 'todo', 'Other secondary care specialty': 'todo', 'Out of Area Agency': 'todo', 'Drug Action Team / Drug Misuse Agency': 'todo', 'Other service or agency': 'todo', 'Single Point of Access Service': 'todo', 'Internal Referral': 'todo', 'CAMHS Core/Step down': 'todo', 'CAMHS Waiting List': 'todo', 'CAMHS Crisis': 'todo', 'VCS': 'todo', 'Permanent transfer from another Mental Health NHS Trust': 'todo', 'Unknown': 'todo'}}

Source_of_Referrals___EHCP = {'sheet_name': 'Referral Source', 'table_name': 'Source of Referrals - EHCP', 'row_names': ['GP services', 'Other Primary Health Care', 'Self', 'Carer', 'Social Services', 'Education Service', 'Housing Service', 'Police', 'School Nurse', 'Hospital-based Paediatrics', 'Community-based Paediatrics', 'Voluntary Sector', 'Accident And Emergency Department', 'Other secondary care specialty', 'Out of Area Agency', 'Drug Action Team / Drug Misuse Agency', 'Other service or agency', 'Single Point of Access Service', 'Internal Referral', 'CAMHS Core/Step down', 'CAMHS Waiting List', 'CAMHS Crisis', 'VCS', 'Permanent transfer from another Mental Health NHS Trust', 'Unknown'], 'placeholder_text': {'GP services': 'todo', 'Other Primary Health Care': 'todo', 'Self': 'todo', 'Carer': 'todo', 'Social Services': 'todo', 'Education Service': 'todo', 'Housing Service': 'todo', 'Police': 'todo', 'School Nurse': 'todo', 'Hospital-based Paediatrics': 'todo', 'Community-based Paediatrics': 'todo', 'Voluntary Sector': 'todo', 'Accident And Emergency Department': 'todo', 'Other secondary care specialty': 'todo', 'Out of Area Agency': 'todo', 'Drug Action Team / Drug Misuse Agency': 'todo', 'Other service or agency': 'todo', 'Single Point of Access Service': 'todo', 'Internal Referral': 'todo', 'CAMHS Core/Step down': 'todo', 'CAMHS Waiting List': 'todo', 'CAMHS Crisis': 'todo', 'VCS': 'todo', 'Permanent transfer from another Mental Health NHS Trust': 'todo', 'Unknown': 'todo'}}

Source_of_Referrals___CRAVEN = {'sheet_name': 'Referral Source', 'table_name': 'Source of Referrals - CRAVEN', 'row_names': ['GP services', 'Other Primary Health Care', 'Self', 'Carer', 'Social Services', 'Education Service', 'Housing Service', 'Police', 'School Nurse', 'Hospital-based Paediatrics', 'Community-based Paediatrics', 'Voluntary Sector', 'Accident And Emergency Department', 'Other secondary care specialty', 'Out of Area Agency', 'Drug Action Team / Drug Misuse Agency', 'Other service or agency', 'Single Point of Access Service', 'Internal Referral', 'CAMHS Core/Step down', 'CAMHS Waiting List', 'CAMHS Crisis', 'Permanent transfer from another Mental Health NHS Trust', 'VCS', 'Unknown'], 'placeholder_text': {'GP services': 'todo', 'Other Primary Health Care': 'todo', 'Self': 'todo', 'Carer': 'todo', 'Social Services': 'todo', 'Education Service': 'todo', 'Housing Service': 'todo', 'Police': 'todo', 'School Nurse': 'todo', 'Hospital-based Paediatrics': 'todo', 'Community-based Paediatrics': 'todo', 'Voluntary Sector': 'todo', 'Accident And Emergency Department': 'todo', 'Other secondary care specialty': 'todo', 'Out of Area Agency': 'todo', 'Drug Action Team / Drug Misuse Agency': 'todo', 'Other service or agency': 'todo', 'Single Point of Access Service': 'todo', 'Internal Referral': 'todo', 'CAMHS Core/Step down': 'todo', 'CAMHS Waiting List': 'todo', 'CAMHS Crisis': 'todo', 'Permanent transfer from another Mental Health NHS Trust': 'todo', 'VCS': 'todo', 'Unknown': 'todo'}}

Source_of_Referrals___BRADFORD_DISTRICT = {'sheet_name': 'Referral Source', 'table_name': 'Source of Referrals - BRADFORD DISTRICT', 'row_names': ['GP services', 'Other Primary Health Care', 'Self', 'Carer', 'Social Services', 'Education Service', 'Housing Service', 'Police', 'School Nurse', 'Hospital-based Paediatrics', 'Community-based Paediatrics', 'Voluntary Sector', 'Accident And Emergency Department', 'Other secondary care specialty', 'Out of Area Agency', 'Drug Action Team / Drug Misuse Agency', 'Other service or agency', 'Single Point of Access Service', 'Internal Referral', 'CAMHS Core/Step down', 'CAMHS Waiting List', 'CAMHS Crisis', 'Transfer by graduation from Child Adolescent Mental Health Services to Adult', 'VCS', 'Unknown'], 'placeholder_text': {'GP services': 'todo', 'Other Primary Health Care': 'todo', 'Self': 'todo', 'Carer': 'todo', 'Social Services': 'todo', 'Education Service': 'todo', 'Housing Service': 'todo', 'Police': 'todo', 'School Nurse': 'todo', 'Hospital-based Paediatrics': 'todo', 'Community-based Paediatrics': 'todo', 'Voluntary Sector': 'todo', 'Accident And Emergency Department': 'todo', 'Other secondary care specialty': 'todo', 'Out of Area Agency': 'todo', 'Drug Action Team / Drug Misuse Agency': 'todo', 'Other service or agency': 'todo', 'Single Point of Access Service': 'todo', 'Internal Referral': 'todo', 'CAMHS Core/Step down': 'todo', 'CAMHS Waiting List': 'todo', 'CAMHS Crisis': 'todo', 'Transfer by graduation from Child Adolescent Mental Health Services to Adult': 'todo', 'VCS': 'todo', 'Unknown': 'todo'}}

No__of_CYP_receiving_a_second_attended_contact_with_mental_health_services_ = {'sheet_name': 'Two attended contacts data', 'table_name': 'No. of CYP receiving a second attended contact with mental health services*', 'row_names': ['All', 'CIC/CLA', 'SEN', 'EHCP', 'CRAVEN', 'BRADFORD DISTRICT'], 'placeholder_text': {'All': 'todo', 'CIC/CLA': 'todo', 'SEN': 'todo', 'EHCP': 'todo', 'CRAVEN': 'todo', 'BRADFORD DISTRICT': 'todo'}}

__Figure_derived_from_MYMUP_Data__not_MHSDS__MHSDS_figure_is_likely_to_be_lower_due_to_uniqueness_across_the_wider_population_ = {'sheet_name': 'Two attended contacts data', 'table_name': '* Figure derived from MYMUP Data, not MHSDS. MHSDS figure is likely to be lower due to uniqueness across the wider population.', 'row_names': [], 'placeholder_text': {}}

DNAs_and_cancellations = {'sheet_name': 'DNA', 'table_name': 'DNAs and cancellations', 'row_names': ['All DNA Appointments', 'All Cancelled by patient', 'All Cancelled by Provider', 'CIC/CLA DNA Appointments', 'CIC/CLA Cancelled by patient', 'CIC/CLA Cancelled by Provider', 'SEN DNA Appointments', 'SEN Cancelled by patient', 'SEN Cancelled by Provider', 'EHCP DNA Appointments', 'EHCP Cancelled by patient', 'EHCP Cancelled by Provider', 'CRAVEN DNA Appointments', 'CRAVEN Cancelled by patient', 'CRAVEN Cancelled by Provider', 'BRADFORD DISTRICT DNA Appointments', 'BRADFORD DISTRICT Cancelled by patient', 'BRADFORD DISTRICT Cancelled by Provider'], 'placeholder_text': {'All DNA Appointments': 'todo', 'All Cancelled by patient': 'todo', 'All Cancelled by Provider': 'todo', 'CIC/CLA DNA Appointments': 'todo', 'CIC/CLA Cancelled by patient': 'todo', 'CIC/CLA Cancelled by Provider': 'todo', 'SEN DNA Appointments': 'todo', 'SEN Cancelled by patient': 'todo', 'SEN Cancelled by Provider': 'todo', 'EHCP DNA Appointments': 'todo', 'EHCP Cancelled by patient': 'todo', 'EHCP Cancelled by Provider': 'todo', 'CRAVEN DNA Appointments': 'todo', 'CRAVEN Cancelled by patient': 'todo', 'CRAVEN Cancelled by Provider': 'todo', 'BRADFORD DISTRICT DNA Appointments': 'todo', 'BRADFORD DISTRICT Cancelled by patient': 'todo', 'BRADFORD DISTRICT Cancelled by Provider': 'todo'}}

Goals_Based_Outcomes = {'sheet_name': 'Outcome Data', 'table_name': 'Goals Based Outcomes', 'row_names': ['Number All Initials completed', 'Number All Follow ups completed', 'Average Initial score', 'Average Follow up score', 'Number CIC/CLA Initials completed', 'Number CIC/CLA Follow ups completed', 'Average CIC/CLA Initial score', 'Average CIC/CLA Follow up score', 'Number SEN Initials completed', 'Number SEN Follow ups completed', 'Average SEN Initial score', 'Average SEN Follow up score', 'Number EHCP Initials completed', 'Number EHCP Follow ups completed', 'Average EHCP Initial score', 'Average EHCP Follow up score', 'Number CRAVEN Initials completed', 'Number CRAVEN Follow ups completed', 'Average CRAVEN Initial score', 'Average CRAVEN Follow up score', 'Number BRADFORD DISTRICT Initials completed', 'Number BRADFORD DISTRICT Follow ups completed', 'Average BRADFORD DISTRICT Initial score', 'Average BRADFORD DISTRICT Follow up score'], 'placeholder_text': {'Number All Initials completed': 'todo', 'Number All Follow ups completed': 'todo', 'Average Initial score': 'todo', 'Average Follow up score': 'todo', 'Number CIC/CLA Initials completed': 'todo', 'Number CIC/CLA Follow ups completed': 'todo', 'Average CIC/CLA Initial score': 'todo', 'Average CIC/CLA Follow up score': 'todo', 'Number SEN Initials completed': 'todo', 'Number SEN Follow ups completed': 'todo', 'Average SEN Initial score': 'todo', 'Average SEN Follow up score': 'todo', 'Number EHCP Initials completed': 'todo', 'Number EHCP Follow ups completed': 'todo', 'Average EHCP Initial score': 'todo', 'Average EHCP Follow up score': 'todo', 'Number CRAVEN Initials completed': 'todo', 'Number CRAVEN Follow ups completed': 'todo', 'Average CRAVEN Initial score': 'todo', 'Average CRAVEN Follow up score': 'todo', 'Number BRADFORD DISTRICT Initials completed': 'todo', 'Number BRADFORD DISTRICT Follow ups completed': 'todo', 'Average BRADFORD DISTRICT Initial score': 'todo', 'Average BRADFORD DISTRICT Follow up score': 'todo'}}

All_Goal_Themes = {'sheet_name': 'Goal Themes', 'table_name': 'All Goal Themes', 'row_names': ['Being able to maintain and build positive relationships', 'Being able to support others', 'Being better at managing my emotional wellbeing', 'Being better at managing risks and feeling safer', 'Covid-19 Support', 'Improving my confidence and self esteem', 'Improving my physical wellbeing', 'Reducing my isolation', 'Understanding who I am', 'TOTAL'], 'placeholder_text': {'Being able to maintain and build positive relationships': 'todo', 'Being able to support others': 'todo', 'Being better at managing my emotional wellbeing': 'todo', 'Being better at managing risks and feeling safer': 'todo', 'Covid-19 Support': 'todo', 'Improving my confidence and self esteem': 'todo', 'Improving my physical wellbeing': 'todo', 'Reducing my isolation': 'todo', 'Understanding who I am': 'todo', 'TOTAL': 'todo'}}

CIC_Goal_Themes = {'sheet_name': 'Goal Themes', 'table_name': 'CIC Goal Themes', 'row_names': ['Being able to maintain and build positive relationships', 'Being able to support others', 'Being better at managing my emotional wellbeing', 'Being better at managing risks and feeling safer', 'Covid-19 Support', 'Improving my confidence and self esteem', 'Improving my physical wellbeing', 'Reducing my isolation', 'Understanding who I am', 'TOTAL'], 'placeholder_text': {'Being able to maintain and build positive relationships': 'todo', 'Being able to support others': 'todo', 'Being better at managing my emotional wellbeing': 'todo', 'Being better at managing risks and feeling safer': 'todo', 'Covid-19 Support': 'todo', 'Improving my confidence and self esteem': 'todo', 'Improving my physical wellbeing': 'todo', 'Reducing my isolation': 'todo', 'Understanding who I am': 'todo', 'TOTAL': 'todo'}}

SEN_Goal_Themes = {'sheet_name': 'Goal Themes', 'table_name': 'SEN Goal Themes', 'row_names': ['Being able to maintain and build positive relationships', 'Being able to support others', 'Being better at managing my emotional wellbeing', 'Being better at managing risks and feeling safer', 'Covid-19 Support', 'Improving my confidence and self esteem', 'Improving my physical wellbeing', 'Reducing my isolation', 'Understanding who I am', 'TOTAL'], 'placeholder_text': {'Being able to maintain and build positive relationships': 'todo', 'Being able to support others': 'todo', 'Being better at managing my emotional wellbeing': 'todo', 'Being better at managing risks and feeling safer': 'todo', 'Covid-19 Support': 'todo', 'Improving my confidence and self esteem': 'todo', 'Improving my physical wellbeing': 'todo', 'Reducing my isolation': 'todo', 'Understanding who I am': 'todo', 'TOTAL': 'todo'}}

EHCP_Goal_Themes = {'sheet_name': 'Goal Themes', 'table_name': 'EHCP Goal Themes', 'row_names': ['Being able to maintain and build positive relationships', 'Being able to support others', 'Being better at managing my emotional wellbeing', 'Being better at managing risks and feeling safer', 'Covid-19 Support', 'Improving my confidence and self esteem', 'Improving my physical wellbeing', 'Reducing my isolation', 'Understanding who I am', 'TOTAL'], 'placeholder_text': {'Being able to maintain and build positive relationships': 'todo', 'Being able to support others': 'todo', 'Being better at managing my emotional wellbeing': 'todo', 'Being better at managing risks and feeling safer': 'todo', 'Covid-19 Support': 'todo', 'Improving my confidence and self esteem': 'todo', 'Improving my physical wellbeing': 'todo', 'Reducing my isolation': 'todo', 'Understanding who I am': 'todo', 'TOTAL': 'todo'}}

CRAVEN_Goal_Themes = {'sheet_name': 'Goal Themes', 'table_name': 'CRAVEN Goal Themes', 'row_names': ['Being able to maintain and build positive relationships', 'Being able to support others', 'Being better at managing my emotional wellbeing', 'Being better at managing risks and feeling safer', 'Covid-19 Support', 'Improving my confidence and self esteem', 'Improving my physical wellbeing', 'Reducing my isolation', 'Understanding who I am', 'TOTAL'], 'placeholder_text': {'Being able to maintain and build positive relationships': 'todo', 'Being able to support others': 'todo', 'Being better at managing my emotional wellbeing': 'todo', 'Being better at managing risks and feeling safer': 'todo', 'Covid-19 Support': 'todo', 'Improving my confidence and self esteem': 'todo', 'Improving my physical wellbeing': 'todo', 'Reducing my isolation': 'todo', 'Understanding who I am': 'todo', 'TOTAL': 'todo'}}

Bradford_District_Goal_Themes = {'sheet_name': 'Goal Themes', 'table_name': 'Bradford District Goal Themes', 'row_names': ['Being able to maintain and build positive relationships', 'Being able to support others', 'Being better at managing my emotional wellbeing', 'Being better at managing risks and feeling safer', 'Covid-19 Support', 'Improving my confidence and self esteem', 'Improving my physical wellbeing', 'Reducing my isolation', 'Understanding who I am', 'TOTAL'], 'placeholder_text': {'Being able to maintain and build positive relationships': 'todo', 'Being able to support others': 'todo', 'Being better at managing my emotional wellbeing': 'todo', 'Being better at managing risks and feeling safer': 'todo', 'Covid-19 Support': 'todo', 'Improving my confidence and self esteem': 'todo', 'Improving my physical wellbeing': 'todo', 'Reducing my isolation': 'todo', 'Understanding who I am': 'todo', 'TOTAL': 'todo'}}

Overall_Discharges = {'sheet_name': 'Discharge Data', 'table_name': 'Overall Discharges', 'row_names': ['Number completed treatment', 'Number inappropriate referrals', 'Number who could not be contacted', 'Number disengaged', 'Number signposted to another CCG provider', 'Not Disclosed'], 'placeholder_text': {'Number completed treatment': 'todo', 'Number inappropriate referrals': 'todo', 'Number who could not be contacted': 'todo', 'Number disengaged': 'todo', 'Number signposted to another CCG provider': 'todo', 'Not Disclosed': 'todo'}}

Discharges___CIC_CLA = {'sheet_name': 'Discharge Data', 'table_name': 'Discharges - CIC/CLA', 'row_names': ['Number completed treatment', 'Number inappropriate referrals', 'Number who could not be contacted', 'Number disengaged', 'Number signposted to another CCG provider', 'Not Disclosed'], 'placeholder_text': {'Number completed treatment': 'todo', 'Number inappropriate referrals': 'todo', 'Number who could not be contacted': 'todo', 'Number disengaged': 'todo', 'Number signposted to another CCG provider': 'todo', 'Not Disclosed': 'todo'}}

Discharges___SEN = {'sheet_name': 'Discharge Data', 'table_name': 'Discharges - SEN', 'row_names': ['Number completed treatment', 'Number inappropriate referrals', 'Number who could not be contacted', 'Number disengaged', 'Number signposted to another CCG provider', 'Not Disclosed'], 'placeholder_text': {'Number completed treatment': 'todo', 'Number inappropriate referrals': 'todo', 'Number who could not be contacted': 'todo', 'Number disengaged': 'todo', 'Number signposted to another CCG provider': 'todo', 'Not Disclosed': 'todo'}}

Discharges___EHCP = {'sheet_name': 'Discharge Data', 'table_name': 'Discharges - EHCP', 'row_names': ['Number completed treatment', 'Number inappropriate referrals', 'Number who could not be contacted', 'Number disengaged', 'Number signposted to another CCG provider'], 'placeholder_text': {'Number completed treatment': 'todo', 'Number inappropriate referrals': 'todo', 'Number who could not be contacted': 'todo', 'Number disengaged': 'todo', 'Number signposted to another CCG provider': 'todo'}}

Discharges___CRAVEN = {'sheet_name': 'Discharge Data', 'table_name': 'Discharges - CRAVEN', 'row_names': ['Number completed treatment', 'Number inappropriate referrals', 'Number who could not be contacted', 'Number disengaged', 'Number signposted to another CCG provider'], 'placeholder_text': {'Number completed treatment': 'todo', 'Number inappropriate referrals': 'todo', 'Number who could not be contacted': 'todo', 'Number disengaged': 'todo', 'Number signposted to another CCG provider': 'todo'}}

Discharges___BRADFORD_DISTRICT = {'sheet_name': 'Discharge Data', 'table_name': 'Discharges - BRADFORD DISTRICT', 'row_names': ['Number completed treatment', 'Number inappropriate referrals', 'Number who could not be contacted', 'Number disengaged', 'Number signposted to another CCG provider', 'Not Disclosed'], 'placeholder_text': {'Number completed treatment': 'todo', 'Number inappropriate referrals': 'todo', 'Number who could not be contacted': 'todo', 'Number disengaged': 'todo', 'Number signposted to another CCG provider': 'todo', 'Not Disclosed': 'todo'}}

Overall_Number_on_Waiting_list__CYP_referred_but_yet_to_attend_1st_appointment_ = {'sheet_name': 'Wait List Data', 'table_name': 'Overall Number on Waiting list (CYP referred but yet to attend 1st appointment)', 'row_names': ['All', 'CIC/CLA', 'SEN', 'EHCP', 'CRAVEN', 'BRADFORD DISTRICT'], 'placeholder_text': {'All': 'todo', 'CIC/CLA': 'todo', 'SEN': 'todo', 'EHCP': 'todo', 'CRAVEN': 'todo', 'BRADFORD DISTRICT': 'todo'}}

Overall_Wait_Times = {'sheet_name': 'Wait Times', 'table_name': 'Overall Wait Times', 'row_names': ['Average Weeks from referral to 1st attended contact/indirect', 'Average Weeks from referral to 2nd attended contact/indirect', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect'], 'placeholder_text': {'Average Weeks from referral to 1st attended contact/indirect': 'todo', 'Average Weeks from referral to 2nd attended contact/indirect': 'todo', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect': 'todo'}}

CIC_CLA_Wait_Times = {'sheet_name': 'Wait Times', 'table_name': 'CIC/CLA Wait Times', 'row_names': ['Average Weeks from referral to 1st attended contact/indirect', 'Average Weeks from referral to 2nd attended contact/indirect', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect'], 'placeholder_text': {'Average Weeks from referral to 1st attended contact/indirect': 'todo', 'Average Weeks from referral to 2nd attended contact/indirect': 'todo', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect': 'todo'}}

SEN_Wait_Times = {'sheet_name': 'Wait Times', 'table_name': 'SEN Wait Times', 'row_names': ['Average Weeks from referral to 1st attended contact/indirect', 'Average Weeks from referral to 2nd attended contact/indirect', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect'], 'placeholder_text': {'Average Weeks from referral to 1st attended contact/indirect': 'todo', 'Average Weeks from referral to 2nd attended contact/indirect': 'todo', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect': 'todo'}}

EHCP_Wait_Times = {'sheet_name': 'Wait Times', 'table_name': 'EHCP Wait Times', 'row_names': ['Average Weeks from referral to 1st attended contact/indirect', 'Average Weeks from referral to 2nd attended contact/indirect', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect'], 'placeholder_text': {'Average Weeks from referral to 1st attended contact/indirect': 'todo', 'Average Weeks from referral to 2nd attended contact/indirect': 'todo', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect': 'todo'}}

CRAVEN_Wait_Times = {'sheet_name': 'Wait Times', 'table_name': 'CRAVEN Wait Times', 'row_names': ['Average Weeks from referral to 1st attended contact/indirect', 'Average Weeks from referral to 2nd attended contact/indirect', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect'], 'placeholder_text': {'Average Weeks from referral to 1st attended contact/indirect': 'todo', 'Average Weeks from referral to 2nd attended contact/indirect': 'todo', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect': 'todo'}}

BRADFORD_DISTRICT_Wait_Times = {'sheet_name': 'Wait Times', 'table_name': 'BRADFORD DISTRICT Wait Times', 'row_names': ['Average Weeks from referral to 1st attended contact/indirect', 'Average Weeks from referral to 2nd attended contact/indirect', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect'], 'placeholder_text': {'Average Weeks from referral to 1st attended contact/indirect': 'todo', 'Average Weeks from referral to 2nd attended contact/indirect': 'todo', 'Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect': 'todo'}}

Yim_Live = {'sheet_name': 'YIM LIVE & KCU Delivery', 'table_name': 'Yim Live', 'row_names': ['Number Sessions', 'Number Participants'], 'placeholder_text': {'Number Sessions': 'todo', 'Number Participants': 'todo'}}

KCU = {'sheet_name': 'YIM LIVE & KCU Delivery', 'table_name': 'KCU', 'row_names': ['Number Schools/Youth Settings', 'Number Participants'], 'placeholder_text': {'Number Schools/Youth Settings': 'todo', 'Number Participants': 'todo'}}

all_configs = [Overall_caseload_and_referrals, CIC_CLA_caseload_and_referrals, SEN_caseload_and_referrals, EHCP_caseload_and_referrals, CRAVEN_caseload_and_referrals, BRADFORD_DISTRICT_caseload_and_referrals, All_Referrals_by_demographics, All_CIC_CLA_Referrals_by_demographics, All_SEN_Referrals_by_demographics, All_EHCP_Referrals_by_demographics, All_CRAVEN_Referrals_by_demographics, BRADFORD_DISTRICT_Referrals_by_demographics, Source_of_All_Referrals, Source_of_Referrals___CIC_CLA, Source_of_Referrals___SEN, Source_of_Referrals___EHCP, Source_of_Referrals___CRAVEN, Source_of_Referrals___BRADFORD_DISTRICT, No__of_CYP_receiving_a_second_attended_contact_with_mental_health_services_, __Figure_derived_from_MYMUP_Data__not_MHSDS__MHSDS_figure_is_likely_to_be_lower_due_to_uniqueness_across_the_wider_population_, DNAs_and_cancellations, Goals_Based_Outcomes, All_Goal_Themes, CIC_Goal_Themes, SEN_Goal_Themes, EHCP_Goal_Themes, CRAVEN_Goal_Themes, Bradford_District_Goal_Themes, Overall_Discharges, Discharges___CIC_CLA, Discharges___SEN, Discharges___EHCP, Discharges___CRAVEN, Discharges___BRADFORD_DISTRICT, Overall_Number_on_Waiting_list__CYP_referred_but_yet_to_attend_1st_appointment_, Overall_Wait_Times, CIC_CLA_Wait_Times, SEN_Wait_Times, EHCP_Wait_Times, CRAVEN_Wait_Times, BRADFORD_DISTRICT_Wait_Times, Yim_Live, KCU]